server:
  port: 8001

spring:
  application:
    name: hystrix-payment-service

eureka:
  instance:
    instance-id: hystrix-payment-8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
  client:
    # 表示是否将自己注册进EurekaServer
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka