server:
  port: 7002

eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka7002.com
  # 自我保护模式开关
  #  server:
  #    enable-self-preservation: false
  client:
    # false表示不向注册中心注册自己。
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # Eureka 集群配置
      defaultZone: http://eureka7001.com:7001/eureka