server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样率值介于 0 到 1 之间，1 则表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_service?useUnicode=true&characterEncoding=UTF-8&useSSl=false&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  type-aliases-package: micro.service.cloud.entity
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    instance-id: payment-8001
    #访问路径可以显示IP地址
    prefer-ip-address: true
    # 向Eureka Server发送心跳间隔(默认30秒)
#    lease-renewal-interval-in-seconds: 1
    # Eureka Server服务端在收到最后一次心跳等待时间上限(默认90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
  client:
    # 表示是否将自己注册进EurekaServer
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka