server:
  port: 3344

spring:
  application:
    name: config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      label: master # 读取分支
      server:
        git:
          uri: https://github.com/WangYG3022/spring-cloud-config-center.git # git仓库名字
  # RabbitMQ 连接配置
  rabbitmq:
    host: wang.aliyun.com
    port: 5672
    username: guest
    password: guest
# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# RabbitMQ相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
